title: EduSense
theme: jekyll-theme-minimal
baseurl: "/Tempered-AI"

logo: /assets/images/logo.png

include:
  - assets/css

plugins:
  - jekyll-feed

github:
  repository: ODU-CS410-SU25-EMERALD/fy25-06-Emerald-TemperedAI
